insert into armario (id_armario, num_prendas) values (-1, 16);
insert into armario (id_armario, num_prendas) values (-2, 0);

insert into usuario (id_user, nombre, apellido, genero, correo, nickname, password, ciudad, celular, armario_id_armario) values (-1, 'Juan Camilo', 'Chafloque Mesia', 'Masculino', 'camilochafloque@gmail.com', 'Chafo', 'Chaflo123', 'Bogotá D.C', '3016581019', -1);
insert into usuario (id_user, nombre, apellido, genero, correo, nickname, password, ciudad, celular, armario_id_armario) values (-2, 'Martin', 'Chafloque Mesia', 'Masculino', 'mart.chafloque@gmail.com', 'Mart', 'Martin123', 'Bogotá D.C', '3158281218', -2);

insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-1, 'Superior', 'Camiseta', 2, 2, 'Naranja', false, true, 'Camiseta naranja', '../../../assets/images/Chafo-1.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-2, 'Superior', 'Camisa', 5, 4, 'Azul', true, true, 'Camisa Azul manga larga', '../../../assets/images/Chafo-2.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-3, 'Superior', 'Camisa', 4, 2, 'Verde', false, true, 'Camisa verde manga corta', '../../../assets/images/Chafo-3.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-4, 'Superior', 'Camiseta', 2, 2, 'Azul', false, true, 'Camiseta azul', '../../../assets/images/Chafo-4.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-5, 'Superior', 'Camisa', 3, 2, 'Amarilla', true, true, 'Camisa amarilla manga corta', '../../../assets/images/Chafo-5.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-6, 'Superior', 'Camiseta', 2, 2, 'Roja', false, true, 'Camiseta roja', '../../../assets/images/Chafo-6.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-7, 'Superior', 'Chaqueta', 3, 5, 'Naranja', true, true, 'Hoodie naranja', '../../../assets/images/Chafo-7.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-8, 'Superior', 'Chaqueta', 3, 5, 'Gris', true, true, 'Chaqueta gris', '../../../assets/images/Chafo-8.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-9, 'Inferior', 'Jeans', 3, 3, 'Azul', true, true, 'Jeans azules', '../../../assets/images/Chafo-9.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-10, 'Inferior', 'Jeans', 3, 4, 'Gris', false, true, 'Jeans grises', '../../../assets/images/Chafo-10.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-11, 'Inferior', 'Shorts', 2, 2, 'Beige', false, true, 'Shorts beige', '../../../assets/images/Chafo-11.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-12, 'Inferior', 'Sudadera', 1, 4, 'Naranja', true, true, 'Sudadera naranja', '../../../assets/images/Chafo-12.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-13, 'Zapato', 'Zapatos', 5, 4, 'Gris', true, true, 'Zapatos grises', '../../../assets/images/Chafo-13.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-14, 'Zapato', 'Tennis', 2, 3, 'Gris', false, true, 'Tenis grises', '../../../assets/images/Chafo-14.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-15, 'Accesorio', 'Guantes', 5, 2, 'Marrón', false, true, 'Guantes marrones', '../../../assets/images/Chafo-15.jpg', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-16, 'Accesorio', 'Bufanda', 5, 3, 'Gris', true, true, 'Bufanda gris', '../../../assets/images/Chafo-16.jpg', -1);