insert into armario (id_armario, num_prendas) values (-1, 16);
insert into armario (id_armario, num_prendas) values (-2, 0);

insert into usuario (id_user, nombre, apellido, genero, correo, nickname, password, ciudad, celular, armario_id_armario) values (-1, 'Juan Camilo', 'Chafloque Mesia', 'Masculino', 'camilochafloque@gmail.com', 'Chafo', 'Chaflo123', 'Bogotá D.C', '3016581019', -1);
insert into usuario (id_user, nombre, apellido, genero, correo, nickname, password, ciudad, celular, armario_id_armario) values (-2, 'Martin', 'Chafloque Mesia', 'Masculino', 'mart.chafloque@gmail.com', 'Mart', 'Martin123', 'Bogotá D.C', '3158281218', -2);

insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-1, 'Superior', 'Camiseta', 2, 2, 'Naranja', false, true, 'Camiseta naranja con cuello verde', 'Chafo-1.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-2, 'Superior', 'Camisa', 5, 4, 'Azul', false, true, 'Camisa Azul manga larga', 'Chafo-2.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-3, 'Superior', 'Camisa', 4, 2, 'Verde', false, true, 'Camisa verde manga corta', 'Chafo-3.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-4, 'Superior', 'Camiseta', 2, 2, 'Azul', false, true, 'Camiseta azul', 'Chafo-4.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-5, 'Superior', 'Camisa', 3, 2, 'Amarilla', false, true, 'Camisa amarilla manga corta con cuello rojo', 'Chafo-5.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-6, 'Superior', 'Camiseta', 2, 2, 'Roja', false, true, 'Camiseta roja', 'Chafo-6.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-7, 'Superior', 'Chaqueta', 3, 5, 'Roja', false, true, 'Hoodie rojo', 'Chafo-7.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-8, 'Superior', 'Chaqueta', 3, 5, 'Gris', false, true, 'Chaqueta gris', 'Chafo-8.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-9, 'Inferior', 'Jeans', 3, 3, 'Azul', false, true, 'Jeans azules', 'Chafo-9.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-10, 'Inferior', 'Jeans', 3, 4, 'Gris', false, true, 'Jeans grices', 'Chafo-10.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-11, 'Inferior', 'Shorts', 2, 2, 'Beige', false, true, 'Shorts beige', 'Chafo-11.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-12, 'Inferior', 'Sudadera', 1, 4, 'Naranja', false, true, 'Sudadera naranja', 'Chafo-12.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-13, 'Zapato', 'Zapatos', 5, 4, 'Gris', false, true, 'Zapatos grices', 'Chafo-13.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-14, 'Zapato', 'Tennis', 2, 3, 'Gris', false, true, 'Tennis grices', 'Chafo-14.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-15, 'Accesorio', 'Guantes', 5, 2, 'Azul', false, true, 'Guantes azules', 'Chafo-15.png', -1);
insert into prenda (id_prenda, seccion, tipo, formalidad, abrigo, color, favorito, disponible, descripcion, url, armario_id_armario) values (-16, 'Accesorio', 'Bufanda', 5, 3, 'Amarilla', false, true, 'Bufanda amarilla', 'Chafo-16.png', -1);