### Normal user login
POST http://localhost:8080/login HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

username=user&password=password

### Normal admin login
POST http://localhost:8080/login HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

username=admin&password=password

###
GET http://localhost:8080/armario/Chafo

###
GET http://localhost:8080/api/employees

###
GET http://localhost:8080/armario/Chafo/prendas/inferior

###
GET http://localhost:8080/armario/Chafo/prendas/accesorios

###
PUT http://localhost:8080/agregarPrenda/Chafo
Content-Type: application/json

{
    "seccion": "Superior",
    "tipo": "Sueter",
    "nivel_formalidad": 3,
    "nivel_abrigo": 5,
    "color": "azul",
    "favorito": false,
    "disponible": true,
    "descripcion": "Sueter Azul",
    "img_url": "Chafo-1.png"
}