###
GET http://localhost:8080/findPrenda/-5
###
GET http://localhost:8080/armario/Chafo/prendas/favoritos
###
PUT http://localhost:8080/agregarSuperior/Chafo
Content-Type: application/json

{
    "seccion": "Superior",
    "tipo": "Sueter",
    "formalidad": 3,
    "abrigo": 5,
    "color": "azul",
    "favorito": false,
    "disponible": true,
    "descripcion": "Sueter Azul",
    "url": "Chafo-1.png",
    "manga": "Larga",
    "cuello": "Redondo"
}
###
DELETE http://localhost:8080/eliminarPrenda/-5

###
GET http://localhost:8080/armario/Chafo/prendas/inferior

###
GET http://localhost:8080/armario/Chafo/-1/prendas

###
GET http://localhost:8080/atuendoFecha/2020-05-07

###
PUT http://localhost:8080/modificarFavorito/-5
Content-Type: application/json

{
    "seccion": "Superior",
    "tipo": "Sueter",
    "formalidad": 3,
    "abrigo": 5,
    "color": "azul",
    "favorito": false,
    "disponible": true,
    "descripcion": "Sueter Azul",
    "url": "Chafo-1.png"
}
