###
GET http://localhost:8080/armario/Chafo

###
GET http://localhost:8080/armario/Chafo/prendas/inferior

###
GET http://localhost:8080/armario/Chafo/prendas/accesorios

###
PUT http://localhost:8080/agregarPrenda/Chafo
Content-Type: application/json

{
    "seccion": "Superior",
    "tipo": "Sueter",
    "nivel_formalidad": 3,
    "nivel_abrigo": 5,
    "color": "azul",
    "favorito": false,
    "disponible": true,
    "descripcion": "Sueter Azul",
    "img_url": "Chafo-1.png"
}

###
PUT http://localhost:8080/modificarFavorito/-5

###
PUT http://localhost:8080/modificarDisponible/-2

###
DELETE http://localhost:8080/eliminarPrenda/-5